name: client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  audio_manager: ^0.8.2
  video_player: ^2.4.5
  flutter_native_splash: ^2.2.19
  shared_preferences: ^2.0.6
  firebase_auth: ^5.1.3
  cupertino_icons: ^1.0.6
  appmetrica_plugin: ^2.1.1
  http: ^1.2.1
  cached_network_image: ^3.0.0

  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic1.png"
